package com.generator.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TASK".
 */
@Entity
public class Task {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String text_task;

    @NotNull
    private String date_task;
    private Boolean is_complete;

    @Generated
    public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

    @Generated
    public Task(Long id, String text_task, String date_task, Boolean is_complete) {
        this.id = id;
        this.text_task = text_task;
        this.date_task = date_task;
        this.is_complete = is_complete;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getText_task() {
        return text_task;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText_task(@NotNull String text_task) {
        this.text_task = text_task;
    }

    @NotNull
    public String getDate_task() {
        return date_task;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate_task(@NotNull String date_task) {
        this.date_task = date_task;
    }

    public Boolean getIs_complete() {
        return is_complete;
    }

    public void setIs_complete(Boolean is_complete) {
        this.is_complete = is_complete;
    }

}
